---
booktitle: Proceedings of The KDD'23 Workshop on Causal Discovery, Prediction and
  Decision
shortname: CDPD2023
volume: '218'
year: '2023'
start: 2023-08-07
end: 2023-08-07
published: 2023-07-25
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: CDPD-2023
month: 0
cycles: false
bibtex_editor: Le, Thuc and Li, Jiuyong and Ness, Robert and Triantafillou, Sofia
  and Shimizu, Shohei and Cui, Peng and Kuang, Kun and Pei, Jian and Wang, Fei and
  Prosperi, Mattia
editor:
- given: Thuc
  family: Le
- given: Jiuyong
  family: Li
- given: Robert
  family: Ness
- given: Sofia
  family: Triantafillou
- given: Shohei
  family: Shimizu
- given: Peng
  family: Cui
- given: Kun
  family: Kuang
- given: Jian
  family: Pei
- given: Fei
  family: Wang
- given: Mattia
  family: Prosperi
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The KDD'23 Workshop on Causal Discovery, Prediction and Decision
    Held in Long Beach, USA on 07 August 2023

  Published as Volume 218 by the Proceedings of Machine Learning Research on 25 July 2023.

  Volume Edited by:
    Thuc Le
    Jiuyong Li
    Robert Ness
    Sofia Triantafillou
    Shohei Shimizu
    Peng Cui
    Kun Kuang
    Jian Pei
    Fei Wang
    Mattia Prosperi

  Series Editors:
    Neil D. Lawrence
date_str: 07 Aug
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v218"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v218
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v218
email: ''
conference:
  name: The KDD'23 Workshop on Causal Discovery, Prediction and Decision
  url: http://4llab.net/workshops/CDPD2023/index.html
  location: Long Beach, USA
  dates:
  - 2023-08-07
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v218/CDPD2023.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v218/CDPD2023.bib
